train:
  epochs: 50  
  batch_size: 8  
  lr: 1.0e-3  
  itr_per_epoch: 1.0e+7 
  device: "mps"

diffusion:
  layers: 3  
  channels: 64  
  nheads: 4  
  diffusion_embedding_dim: 64 
  beta_start: 0.0001 
  beta_end: 0.5 
  num_steps: 500 
  schedule: "quad" 
  is_linear: False 

model:
  is_unconditional: 0 
  timeemb: 320  
  featureemb: 8 
  target_strategy: "random"
