train:
  epochs: 1 
  batch_size: 8  
  lr: 1.0e-3  
  itr_per_epoch: 1.0e+7  
  

diffusion:
  layers: 3 
  channels: 128  
  nheads: 4  
  diffusion_embedding_dim: 64  
  beta_start: 0.0001  
  beta_end: 0.5  
  num_steps: 70  
  schedule: "quad"  
  s_linear: True  

model:
  is_unconditional: 0 
  timeemb: 320  
  featureemb: 8  
  target_strategy: "test" 
  num_sample_features: 320 
